import type { Metadata } from "next";
import "./globals.css";
import { Plus_Jakarta_Sans } from 'next/font/google';
import {
    ClerkProvider,
  } from '@clerk/nextjs'



const plusJakartaSans = Plus_Jakarta_Sans({
    subsets: ['latin'],
    display: 'swap',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
        
    console.log('this is layout text')

    return (
        <ClerkProvider 
            signInUrl="/auth"
            signUpUrl="/auth"
            afterSignOutUrl={"/"}>
        <html lang="en" className="min-h-screen">
            <body className={`${plusJakartaSans.className} flex flex-col min-h-screen bg-bg-400`}>
                {children}
            </body>
        </html>
        </ClerkProvider>
    );
}
